config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'users#home'

  get '/auth/google_oauth2/callback', to: 'sessions#omniauth'
 
  resources :animals  do
    resources :reasons, only: [:new, :create, :index] 
  end

resources :sessions, only: [:new, :create, :destroy, :show]

resources :users, only: [:new, :create, :show]

resources :categories, only: [:new, :create, :show]

end

app/models/Reason.rb
class Reason < ApplicationRecord
    belongs_to :user
    belongs_to :animal

end

app/models/animal.rb
class Animal < ApplicationRecord
    has_many :reasons
    has_many :users, through: :reasons
    belongs_to :category
    
  
    validates :name, presence: true
    validates :name, uniqueness: true
    validates :comment, presence: true

    scope :order_by_alphabetically, -> { order(name: :asc) }
    #to apply a scope method just put it as .chain at the end of a controller action

    def self.search_for_animals(search)
        if !search.blank? #if we got something then search
           Animal.where("name like ?", "%#{search}%")
        else
           Animal.all
        end
    end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :animals
    validates :value, presence: true
end

app/models/featurerequested.rb
class Featurerequested < ApplicationRecord
    belongs_to :user
    belongs_to :animal
end

app/models/user.rb
class User < ApplicationRecord
    has_many :reasons
    has_many :animals, -> { distinct }, through: :reasons
    has_secure_password
    #has_secure_password has a validation for password presence
    validates :name, presence: true

    def self.create_from_omniauth(auth)
        User.find_or_create_by(uid: auth['uid'], provider: auth['provider']) do |u|
            u.name = auth['info']['first_name']
            u.password = SecureRandom.hex(16)
        end
    end

end

app/controllers/animals_controller.rb
class AnimalsController < ApplicationController
    before_action :set_up_animal,  :except => [:create]
    before_action :checked_log_in
    
    def index
        @animals = Animal.search_for_animals(params[:name]) #strong params are only needed when we update or create things in the database
    end
   
    
    def new
        @animal = Animal.new
        #brand new comment
    end

    def create
       @animal = current_user.animals.build(animal_params)
       if @animal.valid?
          @animal.save
          redirect_to animal_path(@animal)
       else
        render :new
       end
    end

    def show
        @animal = Animal.find_by(id: params[:id])
    end

    def edit
        @animal = Animal.find_by(id: params[:id])
    end

    def update
        @animal.update(animal_params)
        if @animal.save
        redirect_to animal_path(@animal)
        else
        render 'animals/edit'
        end
    end

    def destroy
        @animal = Animal.find(params[:id])
        rea =  Reason.where(animal_id: @animal.id)
        rea.each do |r|
            r.destroy
        end
        @animal.destroy
        redirect_to user_path(current_user.id)
    end

    private
    
    def animal_params
        params.require(:animal).permit(:name, :comment, :category_id)
    end

    def set_up_animal
        @animal = Animal.find_by(id: params[:id])
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
 
    def current_user
        return unless session[:user_id] 
        @current_user ||= User.find(session[:user_id])
      end

      helper_method :current_user
     
      def logged_in?
        !!session[:user_id]
      end

      helper_method :logged_in?
    
      def checked_log_in
          if !logged_in?
          flash[:notice]= "Hey you aren’t logged in! Fill this in before you do anything."
          redirect_to new_session_path
          end
      end
      
      helper_method :checked_log_in
   
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
    before_action :checked_log_in
    
    def new
        @category = Category.new
    end

    def create
        @category = Category.create(category_params)
            if @category.save
                redirect_to category_path(@category)
            else
            render :new
            end
    end

    def show
        @category = Category.find_by(id: params[:id])
    end

    private
    def category_params
        params.require(:category).permit(:value, :animals)
    end
    
end

app/controllers/reasons_controller.rb
class ReasonsController < ApplicationController
  before_action :checked_log_in
  def new
      @animal = Animal.find_by(id: params[:animal_id])
        if @animal
          @reason = @animal.reasons.build
        else
          @reason = Reason.new
        end
    end

    def create
     #binding.pry
      #animal = Animal.find_by(id: params[:animal_id])
      #reason = animal.reasons.build(reason_params)
      reason = Reason.new(reason_params) 
      reason.user=current_user
        if reason.save
           redirect_to reasons_path
        else
           render 'reasons/new'
        end
    end

    def index
        @animal = Animal.find_by(id: params[:animal_id])
        if @animal
          @reasons = @animal.reasons
        else
          redirect_to user_path(current_user)
        end
    end

    
  private

  def reason_params
    params.require(:reason).permit(:user_id, :animal_id, :words, animal_attributes: [:name])
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new
        @user = User.new
    end

    def create
        user = User.find_by(name: params[:name])
        if user && user.authenticate(params[:password])
            session[:user_id] = user.id

            @user = user
            redirect_to user_path(@user)
        else
            render 'sessions/wrong_password'
        end 
        # binding.pry  
     end

    def show
        session.delete("user_id")
        redirect_to new_session_path  
    end

    def destroy
        #binding.pry
        session.delete("user_id")
        redirect_to new_session_path
    end

    def omniauth #logs users in with omniauth
        user = User.create_from_omniauth(auth)
        if user.valid?
            session[:user_id] = user.id
            redirect_to new_category_path
        else
            flash[:message] = user.errors.full_messages.join(", ")
            redirect_to '/'
        end
    end

    private
    def auth
        request.env['omniauth.auth']
    end
    
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :set_up_users, :except => [:create]
    before_action :checked_log_in, :except => [:new, :create, :home]
    
    def new
      @user = User.new
    end

    def create
      @user = User.new(user_params)
      if @user.valid?
        @user = User.create(user_params)
        session[:user_id] = @user.id
        redirect_to user_path(@user)
      else
        render 'users/new'
      end
    end

    def show
      @user = current_user
      @user = User.find_by(id: params[:id])
    end

    def home
      render 'users/homepage'
    end 
   
    private

    def user_params
      params.require(:user).permit(:name, :password, :password_confirmation)
    end

    def set_up_users
      @user = User.find_by(id: params[:id])
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/animals/_form.html.erb
<h1>A new Animal and any additional comment about them:</h1>

<%= form_for(@animal) do |f|%>
    <%= f.label :name%>
    <%= f.text_field :name %><br><br>
    <%= f.label :comment %>
    <%= f.text_field :comment%><br><br>
    <%= f.label :category_id %>
    <%= f.collection_select :category_id, Category.all, :id, :value %>
    <% if @animal.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@animal.errors.count, "error") %> prohibited this animal from being saved:
      </h2>

      <ul>
      <% @animal.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<%= f.submit %>
<%end%>

app/views/animals/edit.html.erb
<%= render 'form' %> 
<h1>Change what you want in the above fields<h1>

app/views/animals/index.html.erb
<h1> Here you can find all the animals' names and reason our users liked it.</h1><br>
<%= form_tag('/animals', method: :get) do %>
    <div class="form-group">
      <%= label_tag(:name, "Search by animal name here") %>
      <%= text_field_tag(:name, nil, class: "form-control") %><br><br>
        <div class="actions">
        <%= submit_tag("Search") %>
        </div>
<%end%>
  

<%@animals.each do |animal| %> 
        <h3>People like the <%= animal.name %> because: </h3>
        <% animal.reasons.each do |i| %>
            <h3> - <%= i.words %></h3>
        <%end%><br>
    <%end%>

   
    <%= link_to "Back to your profile", user_path(current_user.id) %>

app/views/animals/new.html.erb
<%= render partial: 'form', locals: {animal: @animal}%> 
<h2> On the next page it will show you the animal you make along with your comment.</h2>

app/views/animals/show.html.erb
<h1> Here is the animal you just created </h1>
<h3> Name: <%= @animal.name %></h3><br>
<h3> Your comment: <%=@animal.comment %></h3><br>
<h3> The category for this animal is: <%= @animal.category.value%></h3><br>
<%= link_to "Next step: Give this animal a reason by clicking here.", new_animal_reason_path(@animal) %><br><br>

<%= link_to "Back to your profile", user_path(current_user.id) %>

app/views/categories/new.html.erb
<h1>To start off, make a new category for an animal</h1>
<%= form_for(@category) do |f|%>
    <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:
      </h2>

      <ul>
      <% @category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<%= f.label :"Write it here:" %>
<%= f.text_field :value%><br><br>
<%= f.submit %>
<% end %><br>
<%= link_to "Back to your profile", user_path(current_user.id) %>

app/views/categories/show.html.erb
<h1> Here is the category you just created </h1>
<%= @category.value %><br><br>

<%= link_to "Back to your profile", user_path(current_user.id) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  
    <title>Findyouranimaltoday</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    
  </head>
  
  
  <body>
  
  <div style="background-image: url('https://static.standard.co.uk/s3fs-public/thumbnails/image/2017/12/08/15/snowyanimals0812f.jpg?width=1368&height=912&fit=bounds&format=pjpg&auto=webp&quality=70');">

  <% flash.each do |name, msg| %>
    <%= content_tag :div, msg, class: name %>
  <%end%>
    

    <%= yield %><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>

    </div>
   </style> 
  </body>
</html>

app/views/reasons/index.html.erb
<h1> Here is your new animal</h1><br>
<%= @animal.name.capitalize%><br><br>
<h2>The reasons people like that animal so far...</h2>
<% @reasons.each do |reason| %>
    - <%= reason.words %><br><br>
<%end%><br><br>
    
<%= link_to "Click here to see all animals ever created", animals_path %><br><br>
<%= link_to "Back to your profile", user_path(current_user.id) %>
   

app/views/reasons/new.html.erb
<h1>In this section type in a reason why you like the animal you made and select it form the drop down menu to associate the reason to that animal</h1>

<%= form_for @reason do |f|%>
    <% if !@animal %>
    <%= f.collection_select :animal_id, Animal.all, :id, :name %>
    <%end%>
    <p>Put your reason here:</p>
    <%= f.label :Reason %>
    <%= f.text_field :words%><br><br>
    <br><br><%= f.submit %>
<%end%>

app/views/users/_form.html.erb
<h1>Make your own profile</h1>
<%= form_for @user do |f| %>
    <% if @user.errors.any? %>
      <div id="error_explanation">
        <h2>
          <%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:
        </h2>
  
        <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
  
    <div class="form-group">
      <%= f.label :name %>
      <br>
      <%= f.text_field :name, class: "form-control" %>
    </div>
  
    <div class="form-group">
      <%= f.label :password %>
      <br>
      <%= f.password_field :password, class: "form-control" %>
  
    <div class="actions">
      <br/>
      <%= f.submit class: "btn btn-primary" %>
    </div>
  
<% end %> 

app/views/users/homepage.html.erb
<h1>Welcome to Find your Animal Today! - Where we make an animal and give them a reason why we love them. </h1>
<%= link_to "Sign Up", '/users/new' %><br><br>
<%= link_to "Log in", '/sessions/new' %><br><br>
<%= button_to "Log in with Google", '/auth/google_oauth2' %>
<%= flash[:message] %>

app/views/users/new.html.erb
<%= render 'form' %>

app/views/users/show.html.erb
<h1> Here are all of your animals so far <%=current_user.name%>.</h1>
<h2> If the area down below is blank then it probably means you don't have any animals created yet.</h2>
<h1> Directions for making an animal </h1>
<h2> 1. Make sure you create a category first before you create a new animal! Otherwise the new animal won't know where to belong! </h2>
<h2> 2. Then create a reason for the animal through the make a new animal link. </h2>
<h2> 3. The animal will appear on your screen along with whatever reasons everybody gave about why they it! </h2><br>


<% current_user.animals.each do |animal| %>
   
    <p>Name for this animal:</p>
    <%= animal.name%><br>
    <p>Additional comments for this animal from everyone:</p>
    <%= animal.comment%><br>
    <p>Reason(s) why people have said they liked it:</p>
      <%=animal.reasons.map { |reason| reason.words}.join(", ")%><br><br>
    <%= link_to "Edit this animal's name or comment, and assign it a category.", edit_animal_path(animal) %><br><br>
    
    <%= button_to "Delete Animal", animal_path(animal), method: :delete %><br><br>

    <%= link_to "Click here to make a new reason why you like an animal and associate it to an animal.", new_animal_reason_path(animal) %><br> 

    <h4> Reasons that you make from this page will be associated to your account and appear in this animal list. </h4>
    <h4> Want to make a second reason? You can also click the above link to associate a new reason for the same animal.</h4>
<% end %>

<%= link_to "Make a category for an animal", new_category_path %><br><br>

<%= link_to "Make a new animal and assign a category to it", new_animal_path %><br><br>

<%= link_to "Click here to see all animals ever created by everybody", animals_path %><br><br>

<%= link_to "Log Out", session_path, method: :delete %><br>